export { default as HomePage } from './HomePage/HomePage'
export { default as MoviesOpenPage } from './MoviesOpenPage/MoviesOpenPage'
export { default as MoviesShowsPage } from './MoviesShowsPage/MoviesShowsPage'
export { default as NotFound } from './NotFound/NotFound'
export { default as ShowsOpenPage } from './ShowsOpenPage/ShowsOpenPage'
export { default as SubscriptionPage } from './SubscriptionPage/SubscriptionPage'
export { default as SupportPage } from './SupportPage/SupportPage'
